### ISSUE TITLE
Micro deploy  error

### ISSUE THREAD

**Issue by hanxy** [cloudfoundry-community-attic/bosh-cloudstack-cpi#21]
## My micro_deploy config is:

name: firstbosh
logging:
  level: DEBUG
network:
  type: dynamic

  vip: 10.255.254.4
  cloud_properties:
    network_name: vx_siz
resources:
  persistent_disk: 40960
  cloud_properties:
    instance_type: Small Instance
cloud:
  plugin: cloudstack
  properties:
    cloudstack:
      endpoint: http://10.255.254.233:8080/client/api
      api_key: **************************************
      secret_access_key: ***********************************
      default_key_name: bosh_test
      private_key: ~/.ssh/vkey.pem
      state_timeout: 600
      state_timeout_volume: 1200
      stemcell_public_visibility: true
      default_zone: s_cloud 

```
registry:
  endpoint: http://admin:admin@10.255.254.20:25889
  user: admin
  password: admin
```

---

My Error is:
Connect to agent timeout 
I can see create vm and bind float ip to the vm, but inception server always connect the agent timeout
I can see the log is:
https://vcap:b00tstaroop:10.255.254.4 :6868
user: vcap
password: b00tstraoop

and also I try use this account and password but can't to ssh successfully! 
I try to use root to ssh it by a method successfully and 6868 port is listen, but every micro bosh is stoped in waiting for the agent

**Comment by resouer** [comment]
update & use the latest stemcell please
