### ISSUE TITLE
我运行生成配置文件的脚本是这样的我怎么改啊

### ISSUE THREAD

**Issue by hanxy** [cloudfoundry-community-attic/bosh-cloudstack-cpi#22]
root@v-UQy6yX42pjN:~/hanxy/cf-release# ./generate_deployment_manifest openstack
2014/08/29 16:59:20 error generating manifest: unresolved nodes:
    (( merge )) in ./templates/cf-infrastructure-openstack.yml  meta.openstack
    (( merge )) in ./templates/cf-infrastructure-openstack.yml  meta.floating_static_ips
    (( merge )) in ./templates/cf-infrastructure-openstack.yml  networks
    (( merge )) in ./templates/cf-infrastructure-openstack.yml  properties.cc
    (( jobs.nats_z1.networks.cf1.static_ips.[0] ))  in dynaml   properties.nats.address
    (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))  in dynaml   properties.ccdb.address
    (( merge )) in ./templates/cf-infrastructure-openstack.yml  properties.ccdb.roles.[0].password
    (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))  in dynaml   properties.databases.address
    (( merge )) in ./templates/cf-infrastructure-openstack.yml  properties.databases.roles.[0].password
    (( merge )) in ./templates/cf-infrastructure-openstack.yml  properties.databases.roles.[1].password
    (( merge )) in ./templates/cf-infrastructure-openstack.yml  properties.uaa.clients
    (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))  in dynaml   properties.uaadb.address
    (( merge )) in ./templates/cf-infrastructure-openstack.yml  properties.uaadb.roles.[0].password
    (( meta.floating_static_ips ))  in dynaml   jobs.[0].networks.[0].static_ips
    (( static_ips(0) )) in ./templates/cf-infrastructure-openstack.yml  jobs.[0].networks.[1].static_ips
    (( static_ips(1) )) in ./templates/cf-infrastructure-openstack.yml  jobs.[1].networks.[0].static_ips
    (( static_ips(2) )) in ./templates/cf-infrastructure-openstack.yml  jobs.[2].networks.[0].static_ips
    (( static_ips(3) )) in ./templates/cf-infrastructure-openstack.yml  jobs.[3].networks.[0].static_ips
    (( static_ips(4) )) in ./templates/cf-infrastructure-openstack.yml  jobs.[4].networks.[0].static_ips
    (( static_ips(5) )) in ./templates/cf-infrastructure-openstack.yml  jobs.[5].networks.[0].static_ips
    (( static_ips(6) )) in ./templates/cf-infrastructure-openstack.yml  jobs.[6].networks.[0].static_ips
    (( static_ips(7) )) in ./templates/cf-infrastructure-openstack.yml  jobs.[7].networks.[0].static_ips
    (( static_ips(8, 9, 10) ))  in ./templates/cf-infrastructure-openstack.yml  jobs.[8].networks.[0].static_ips

**Comment by zhigoo** [comment]
openstack? you are sure post this in right palace.

**Comment by resouer** [comment]
invalid
