### ISSUE TITLE
Convert to new External CPI

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community-attic/bosh-cloudstack-cpi#23]
- [ ] extract the bosh-cloudstack-cpi gem with binary executable
- [ ] create bosh-cloudstack-cpi-release with a `cpi` job template

**Comment by resouer** [comment]
We'll looking at it. Thanks for reminding.

**Comment by yudai** [comment]
Are there any documents that describe the specification of external CPI?

**Comment by cppforlife** [comment]
Not yet. I'm planning to write them soon. Will let you guys know.

**Comment by wayneeseguin** [comment]
@cppforlife How about now? ;)

**Comment by gberche-orange** [comment]
As we're studying this, I extracted the following documentation pointers on the external CPI:
- [Stdin/stdout API wiki](https://github.com/cloudfoundry/bosh/wiki/BOSH-CPI-API-v1-%28WIP%29)
- [Sequenting of calls](https://groups.google.com/a/cloudfoundry.org/d/msg/bosh-dev/QbZjCBJwNPE/dazJAUcjIEIJ)
  - _"One way to find out order of all those things is to run bosh-lite and look at the logs. All cpi methods act on some resources that have cloud ids. e.g. attach_disk for example takes vm_cid and disk_cid which means that create_vm and create_disk would be called at some point before this. Important thing to note is that bosh may call any of those methods in a different order depending on the situation as long as bosh is able to provide needed arguments to the methods."_
  - diagrams:
    - [deploy flow](https://github.com/cloudfoundry/bosh-init/blob/master/docs/architecture.md#deploy-command-flow)
    - [delete flow](https://github.com/cloudfoundry/bosh-init/blob/master/docs/architecture.md#delete-command-flow)
- [Reference Implementations of CPI API: openstack in go](https://github.com/frodenas/bosh-openstack-cpi/blob/86469da9dc0782ae9540dcf18e070d31d71bb440/action/concrete_factory.go#L125)

**Comment by lcacciagioni** [comment]
Any news on this? @drnic @yudai?
