### ISSUE TITLE
Default Stemcell Size should be larger than 10GB

### ISSUE THREAD

**Issue by yudai** [cloudfoundry-community-attic/bosh-cloudstack-cpi#4]
The current default stemcell disk size is 2GB. However, this is too small to run general jobs.

**Comment by m1093782566** [comment]
Yeah, we can simply modify the default value to a bigger one such 10GB. However, I think the best solution maybe creating a volume with a specified size.

**Comment by yudai** [comment]
Fixed: https://github.com/cloudfoundry-community/bosh-cloudstack-cpi/commit/fdb7dc439ef1e34234577a40276b6d718c693a6d

**Comment by yudai** [comment]
@m1093782566 Unfortunately, it seems that we cannot create a volume with a specified size. We have to choose a disk offering from provided by CloudStack.

**Comment by m1093782566** [comment]
Indeed, Cloudstack user API provides an interface to create a volume with a
specified size. And ZJU-SEL fog can be an example:
https://github.com/ZJU-SEL/fog/blob/zjudev/lib/fog/cloudstack/models/compute/volume.rb#L36

2013/12/9 Iwasaki Yudai notifications@github.com

**Comment by yudai** [comment]
I tried to add the `size` option to the params to create volumes. However, it raises an error. It seems that the `size` option works with only xvdb drives?

**Comment by m1093782566** [comment]
I am afraid you are right. Different from openstack, cloudstack API does
support create volume only with size parameter. _Either diskOfferingId or
snapshotId must be passed in._
Sorry for wasting your time, you can close this issue now.

2013/12/10 Iwasaki Yudai notifications@github.com

**Comment by yudai** [comment]
Thanks.
