### ISSUE TITLE
What's the real disk device name of a KVM virtual server?

### ISSUE THREAD

**Issue by m1093782566** [cloudfoundry-community-attic/bosh-cloudstack-cpi#7]
When we attach a new volume to VM, from Cloudstack Web console, we can see the start device id of datadisk is equal to 1, and then 2, 3 ... There is no problem with that but I would like to discuss the real device name of the first datadisk, sdb? vdb? or vda?

In my environment, I find the device name of the first datadisk is "vda" instead of "sdb" or "vdb". Of course, it may depends on specified kernel. So, how about add some patches in
https://github.com/cloudfoundry-community/bosh-cloudstack-cpi/blob/master/bosh_cloudstack_cpi/lib/cloud/cloudstack/cloud.rb#L619

**Comment by m1093782566** [comment]
Well, select ubuntu12.04 and ubuntu10.04 when create VM may work around this issue.

**Comment by m1093782566** [comment]
For some ubuntu distributions such as 10.04 and 12.04, Cloudstack takes device name of root disk as "vda" while others' as "sda", so device name of data disk can be "vda" or "sdb". However, Cloudstack-CPI assumes device name of data disk is "sdb" or "vdb" and ignores the possibility of "vda".

So, Hard code[1] ubuntu12.04 or ubuntu10.04 for OS version is not a perfect way for fixing the issue.

What about add some logical judgements here[2]?

[1]
https://github.com/cloudfoundry-community/bosh-cloudstack-cpi/blob/master/bosh_cloudstack_cpi/lib/cloud/cloudstack/stemcell_creator.rb#L88

[2]
https://github.com/cloudfoundry-community/bosh-cloudstack-cpi/blob/master/bosh_cloudstack_cpi/lib/cloud/cloudstack/cloud.rb#L624

**Comment by metahertz** [comment]
Admittedly haven't verified this, but just to add my 10 pence from the back of my mind. 

I believe the SDx/VDx is less about versions of ubuntu and more about wether the VM is paravirtualized (VDx) or full hardware virtualization (emulating SATA SDx device) based on the drivers in use in each of the scenarios. It may be that the older versions are not paravirt-compatible and so KVM is using hardware virtualization by default hence the change in disk names.

Matt

**Comment by yudai** [comment]
If a VM has both `vda` and `sda` devices, that would mean there's something wrong  with the configuration. As @matjohn2 described, `sda` devices are not used for paravirtualized(virtio-enabled) KVM VMs. I suppose that CloudStack basically does not attach both `sda` and `vda` to a single VM.
As far as I know, when the OS TYPE of a VM is `Other Ubuntu`, the VM's root device will be `sda` and additional disk will be `vda`. I think that this is a bug of CloudStack. However, If the OS TYPE is set to Ubuntu 10.04 or 12.04, CloudStack correctly attaches root volumes as `vda`.
It's hard for the CPI to determine an newly attached volume if both `vda` and `vdb` are existing with the current implementation and the specification of CloudStack API. I'm not sure that we can suppose that the possibly combinations are only sda and vda. And if so, how to determine which is the root device?
@m1093782566 Could you please describe the detail of your situation/configuration that raised the problem? I think that we need to discuss if the situation is common.

**Comment by m1093782566** [comment]
I have tested for many Operation Systems. Any ubuntu distribution newer than 10.04 use vda as root disk name and vdb as the first data disk name. If a user carelessly select other OS types such as centos or apple while use Ubuntu distribution as template will cause this issue, that root disk name is sda and first data disk name is vda.

**Comment by yudai** [comment]
I think that selecting other OS TYPEs like centos for Ubuntu templates is an unsupported configuration. Can we ignore that situation? Of course, adding some notes to README for users to choose a correct OS TYPE would be a good idea.

**Comment by metahertz** [comment]
I would agree, misconfiguration of the instance type (if this is proved to be the cause in all the commenters cases) is not something a CPI should be catering for IMHO.

Matt

Iwasaki Yudai notifications@github.com wrote:

I think that selecting other OS TYPEs like centos for Ubuntu templates is an unsupported configuration. Can we ignore that situation?

**Comment by m1093782566** [comment]
I agree too and will update README.md to remind some careless guys just like me! :)
