### ISSUE TITLE
If floating IP is missing in customer network

### ISSUE THREAD

**Issue by m1093782566** [cloudfoundry-community-attic/bosh-cloudstack-cpi#9]
I would like to discuss the issue about floating IPs which are needed to be associated to VMs in advanced zone.

We need to associate floating IPs to VMs such as microbosh and router of cloudfoundry. Usually, these IPs exist in customer network. However, these IPs can be missing in customer network due to some reasons like some careless guys misconfigure it.

What will happen if we neglect this situation? According to the current Cloudstack-CPI, there is no handling mechanism on missing floating addresses[1].

I propose some solutions:

1) If a IP address is not found in customer network, we throw warning or exception to users. And if we regard it as exception, then program breaks down immediately.

2) If we regard IP address missing as just warning and users confirm to associate this new IP, we can create this IP before associating it to VM.

[1]
https://github.com/cloudfoundry-community/bosh-cloudstack-cpi/blob/master/bosh_cloudstack_cpi/lib/cloud/cloudstack/vip_network.rb#L35

**Comment by yudai** [comment]
For your information, the OpenStack CPI and the AWS CPI employed the solution (1).

I think that the solution (2) is a kind behaviour for users, however, it's hard to implement this plan at this moment because the CloudStack API for acquiring a floating IP address doesn't provide a mechanism to specify an exact IP address to be created. I therefore think implementing the (1) is our only possible approach.

**Comment by m1093782566** [comment]
Solved by solution (1).

**Comment by gberche-orange** [comment]
@yudai can you please clarify the floating ip / vip limitation ?

https://github.com/cloudfoundry-community/bosh-cloudstack-cpi#describe-manifest describes advanced zone support

```
    # Only for Advanced zone users
      # You can set floating addresses to jobs
      # Acquire Public IP addresses on your Web UI before deploying
      # (Don't remove `default` network above even if `floating` is added)
      - name: floating
        static_ips:
          - <IP address for Router>
```

whereas https://github.com/cloudfoundry-community/bosh-cloudstack-cpi#sample-templates mentions `Currently the CloudStack CPI does not support VIP networks and Floating IPs.`

I guess this latter comment it outdated?

Besides, is the current CPI able to assign predetermined static private IP mentionned in the manifest (which seems the current practice in the cf-release spiff templates) ?

If not does this imply that the usual spiff templates provided by cf-release that specify IPs for connect jobs together, always have to be patched to use instead FQDN resolved by micro-bosh/full-bosh ?
